service: my-test-php-app

provider:
 name: aws
 runtime: provided
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1

functions:
 api:
   handler: index.php
   layers:
    - arn:aws:lambda:us-east-1:887080169480:layer:php71:6
   events:
     - http: ANY {proxy+}
     - http: ANY /