service: 
    name: my-test-php-app
package:
  exclude:
    - config/config.yml
    - .gitignore
    - .git/**    
provider:
 name: aws
 runtime: provided
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - kms:Decrypt
      Resource: { "Fn::Join" : ["", ["arn:aws:kms:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":key/662c685a-51e7-45a7-ad0d-478863112001" ] ]  }    
functions:
 phpApp:
   handler: index.php
   layers:
    - arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:1
   events:
     - http: ANY {proxy+}
     - http: ANY /
