service: my-test-php-function

custom:
  bucket: kac-test-bucket-for-json

provider:
 name: aws
 runtime: provided
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
   - Effect: Allow
     Action:
       - s3:GetObject
     Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
 api:
   handler: index.php
   layers:
    - arn:aws:lambda:us-east-1:209497400698:layer:php-73:1
   events:
    - s3:
        bucket: ${self:custom.bucket}
        event: s3:ObjectCreated:*