service: 
    name: my-test-php-app

custom:
  bucket: php-app-logs

provider:
 name: aws
 runtime: provided
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"     
functions:
 phpApp:
   handler: index.php
   layers:
    - arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:1
   events:
     - http: ANY {proxy+}
     - http: ANY /
